# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iosApp' do
  use_frameworks!
  use_modular_headers!

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
end